basePath: /
definitions:
  common.ErrorResponse:
    properties:
      details:
        items:
          $ref: '#/definitions/common.FieldError'
        type: array
      error:
        type: string
      message:
        type: string
      path:
        type: string
      status:
        type: integer
      timestamp:
        type: string
    type: object
  common.FieldError:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  instrument.Instrument:
    properties:
      created_At:
        type: string
      exchange:
        type: string
      id:
        type: string
      last_price:
        type: number
      name:
        maxLength: 50
        minLength: 2
        type: string
      symbol:
        maxLength: 50
        minLength: 2
        type: string
      type:
        type: string
      updated_At:
        type: string
    required:
    - name
    - symbol
    - type
    type: object
  user.User:
    properties:
      age:
        type: integer
      email:
        type: string
      firstName:
        maxLength: 50
        minLength: 2
        type: string
      lastName:
        maxLength: 50
        minLength: 2
        type: string
      phone:
        type: string
      status:
        $ref: '#/definitions/user.UserStatus'
      userId:
        type: string
    required:
    - email
    - firstName
    - lastName
    type: object
  user.UserStatus:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - Active
    - InActive
info:
  contact:
    email: chethiya.viharagama@yaalalabs.com
    name: Chethiya Viharagama
    url: http://www.swagger.io/support
  description: This is User Management server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: User Management API
  version: "1.0"
paths:
  /instruments:
    get:
      consumes:
      - application/json
      description: Get all instruments
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/instrument.Instrument'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get all instruments
      tags:
      - instruments
    post:
      consumes:
      - application/json
      description: Create a new instrument
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/instrument.Instrument'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Create a new instrument
      tags:
      - instruments
  /instruments/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing instrument by id
      parameters:
      - description: Instrument ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete instrument by id
      tags:
      - instruments
    get:
      consumes:
      - application/json
      description: Get instrument details by id
      parameters:
      - description: Instrument ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/instrument.Instrument'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get instrument by id
      tags:
      - instruments
    patch:
      consumes:
      - application/json
      description: Update an instrument by id
      parameters:
      - description: Instrument ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/instrument.Instrument'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Update instrument by id
      tags:
      - instruments
  /users:
    get:
      consumes:
      - application/json
      description: Get all users
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Create a new user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete user by id
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get user details by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get user by id
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Update an user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Update user by id
      tags:
      - users
swagger: "2.0"
